export const PDFConst = {
  LOADING: "LOADING",
  LOAD_COMPLETE: "LOAD_COMPLETE",
  START_RENDER_WVS_CONTROL: "START_RENDER_WVS_CONTROL",
  END_RENDER_WVS_CONTROL: "END_RENDER_WVS_CONTROL",
  ADD_CONTROL_TO_PDF: "ADD_CONTROL_TO_PDF",
  REMOVE_ALL_CONTROL_PDF: "REMOVE_ALL_CONTROL_PDF",
};
